tap  'caskroom/versions' # for e.g. Java 9
brew 'mas' # for Mac App Store stuff

# Bash and general CLI tools
brew 'bash-completion'
brew 'coreutils'
brew 'jq'
brew 'tree'
brew 'wget'

# Cloud CLIs
cask 'google-cloud-sdk'
brew 'awscli'
brew 'kubernetes-cli'

# Editors
brew 'emacs', args: ['with-cocoa', 'with-gnutls', 'srgb']
cask 'macdown'

# DBs
brew 'mongo'
brew 'postgres'

# JS
brew 'node' # lots of internet noise around this; evaluate.
brew 'npm'
brew 'yarn'

# Ruby
brew 'rbenv'

# Python
brew 'pyenv'
brew 'pyenv-virtualenv'

# Javascript
brew 'nodenv'

# Java
brew 'jenv'
cask 'java7'
cask 'java'
cask 'java9-beta'

# OS/Environment mod apps
cask 'dropbox'
cask 'slate'

# Plane, lathe, chisel, etc.
cask 'google-chrome'
cask 'iterm2'
cask 'postman'

# All mas stuff so that password prompt comes as late as possible
mas '1Password', id: 443987910
mas 'Xcode', id: 497799835
mas 'Kindle', id: 405399194
mas 'OmniFocus', id: 867299399
mas 'Slack', id: 803453959 # TODO not sure this needs a mas install
                           # vs. e.g. cask; what's the benefit?
