#!/usr/bin/env bash

png_to_icns() {
  local usage="usage: png_to_icons <a_1024_x_1024px_png_file.png>"
  local height="-1"
  local width="-1"
  read height width <<< "$(
      file "$1" | \
      sed -E 's/.*, ([0-9]+) x ([0-9]+).*/\1 \2/'
  )"
  if [[ -z "$1" ]] || [[ $height -ne 1024 ]] || [[ $width -ne 1024 ]]; then
    echo $usage 1>&2
    return 1
  fi
  png_file=$(basename $1)
  local no_ext="${png_file%.*}"
  
  mkdir -p "$no_ext.iconset"
  sips -z 16 16     "$1" --out "$no_ext.iconset"/icon_16x16.png
  sips -z 32 32     "$1" --out "$no_ext.iconset"/icon_16x16@2x.png
  sips -z 32 32     "$1" --out "$no_ext.iconset"/icon_32x32.png
  sips -z 64 64     "$1" --out "$no_ext.iconset"/icon_32x32@2x.png
  sips -z 128 128   "$1" --out "$no_ext.iconset"/icon_128x128.png
  sips -z 256 256   "$1" --out "$no_ext.iconset"/icon_128x128@2x.png
  sips -z 256 256   "$1" --out "$no_ext.iconset"/icon_256x256.png
  sips -z 512 512   "$1" --out "$no_ext.iconset"/icon_256x256@2x.png
  sips -z 512 512   "$1" --out "$no_ext.iconset"/icon_512x512.png
  cp "$1" "$no_ext.iconset"/icon_512x512@2x.png
  iconutil -c icns "$no_ext.iconset"
}
