#!/bin/bash

# bash_profile

declare -a files=(
    $HOME/.tilde/bash/bash_options # Options
    $HOME/.tilde/bash/bash_exports # Exports
    $HOME/.tilde/bash/bash_aliases # Aliases
    $HOME/.tilde/bash/bash_eliases # For Eli
    $HOME/.tilde/bash/functions/* # Functions
    $HOME/.tilde/bash/bash_prompt # Custom bash prompt
    $HOME/.bash_profile.local # Local and private settings not under version control (e.g. git credentials)
    $HOME/.tilde/bash/bash_paths # Path modifications (must source after `.bash_profile.local` in case of custom `brew` location)
    /usr/local/bin/virtualenvwrapper.sh # Python virtualenvwrapper
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
    fi
done

unset files

# We only use `brew` after it has been added to the PATH
# Source Bash completion (installed via Homebrew)
bash_completion_path="$(brew --prefix)/etc/bash_completion"
if [[ -r $bash_completion_path ]]; then
    source $bash_completion_path
fi

# start *env shims
declare -a shims=(
    jenv
    nodenv
    pyenv
    rbenv
)
for index in ${!shims[*]}
do
    shim=${shims[$index]}
    hash ${shim} &> /dev/null && eval "$(${shim} init -)"
done
