#!/bin/bash

# bash_paths

# Directories to be prepended to PATH
declare -a dirs_to_prepend=(
    "/usr/local/bin" # Ensure that this bin always takes precedence over `/usr/bin`
    "$(yarn global bin)"
)

# Directories to be appended to PATH
declare -a dirs_to_append=(
    "/usr/bin"
    "$HOME/bin"
    "$HOME/.dotfiles/bin"
    "$HOME/.rbenv/bin"
    "$(brew --prefix coreutils)/libexec/gnubin" # Add brew-installed GNU core utilities bin
    "$(brew --prefix)/share/npm/bin" # Add npm-installed package bin
    "$HOME/.cabal/bin"
    "$HOME/.ghcup/bin"
    "$GOPATH/bin"
    "$(brew --prefix)/opt/go/libexec/bin"
    "$HOME/Library/Android/sdk/tools"
    "$HOME/Library/Android/sdk/platform-tools"
    "$HOME/.cargo/bin"
    "$HOME/bin"
)

# Prepend directories to PATH
for index in ${!dirs_to_prepend[*]}
do
    if [ -d "${dirs_to_prepend[$index]}" ]; then
        # If these dirs exist, then prepend them to existing PATH
        PATH="${dirs_to_prepend[$index]}:$PATH"
    fi
done

# Append directories to PATH
for index in ${!dirs_to_append[*]}
do
    if [ -d "${dirs_to_append[$index]}" ]; then
        # If these dirs exist, then append them to existing PATH
        PATH="$PATH:${dirs_to_append[$index]}"
    fi
done

unset dirs_to_prepend dirs_to_append

export PATH
export GOPATH
