#!/bin/bash

# bash_options

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Other history tweaks
trap "history -a" EXIT # all ttys write to bash history on exit


# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob
