#!/bin/bash

# bash_profile

declare -a files=(
    "$HOME/.tilde/bash/bash_options" # Options
    "$HOME/.tilde/bash/bash_exports" # Exports
    "$HOME/.tilde/bash/bash_aliases" # Aliases
    "$HOME/.tilde/bash/bash_eliases" # For Eli
    "$HOME/.tilde/bash/bash_prompt" # Custom bash prompt
    "$HOME/.bash_profile.local" # Local and private settings not under version control (e.g. git credentials)
    "$HOME/.tilde/bash/bash_paths" # Path modifications (must source after `.bash_profile.local` in case of custom `brew` location)
    $HOME/.tilde/bash/functions/* # Functions (don't quote this, otherwise globbing will fail)
)
for index in ${!files[*]}
do
    if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
    fi
done
unset files

# We only use `brew` after it has been added to the PATH, but want to
# source these files based on wherever brew is.
brew_prefix=$(brew --prefix)
declare -a post_brew_files=(
    "$brew_prefix/etc/bash_completion"
    "$brew_prefix/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc"
    "$brew_prefix/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc"
)
unset brew_prefix

for index in ${!post_brew_files[*]}
do
    if [[ -r ${post_brew_files[$index]} ]]; then
        source ${post_brew_files[$index]}
    fi
done
unset post_brew_files

# Trial asdf (https://github.com/asdf-vm/asdf) for cross-lang version + env management
if [[ -r "/usr/local/opt/asdf/asdf.sh" ]]; then
    source /usr/local/opt/asdf/asdf.sh
fi
