#!/bin/bash

# inputrc

# Use case-insensitive TAB autocompletion
set completion-ignore-case on

# Auto list tab completions (use instead of TAB-cycling)
set show-all-if-ambiguous on

# Use the string that has already been typed as the prefix for searching
# through commands (i.e. more intelligent Up/Down-arrow behavior)
"\e[B": history-search-forward
"\e[A": history-search-backward

# Stop old-school ascii/8th-bit cruft from interfering with Unicode entry
set meta-flag on
set input-meta on
set output-meta on
set convert-meta off
